import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

FLAG_COLORS = {
    "grounded": colors.HexColor("#1a6b45"),
    "weak": colors.HexColor("#96650a"),
    "unverified": colors.HexColor("#a4322a"),
}


def build_audit_pdf(report: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=18 * mm, rightMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], fontSize=16,
                                  textColor=colors.HexColor("#0f2a36"), spaceAfter=4)
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"], fontSize=9,
                                 textColor=colors.HexColor("#6b7f87"), spaceAfter=14)
    cell_style = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=8.5, leading=11)
    header_style = ParagraphStyle("HeaderCell", parent=styles["Normal"], fontSize=8.5,
                                   textColor=colors.white, leading=11)

    elements = []
    elements.append(Paragraph("VeriMed (Research Edition) — Grounding &amp; Attribution Audit Log", title_style))
    elements.append(Paragraph(
        f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} &nbsp;|&nbsp; "
        f"Overall hallucination risk: {round(report['overall_risk'] * 100, 1)}% "
        f"&nbsp;|&nbsp; Method: TF-IDF cosine similarity",
        meta_style,
    ))

    table_data = [[
        Paragraph("Claim", header_style), Paragraph("Closest Source Match", header_style),
        Paragraph("Score", header_style), Paragraph("Flag", header_style),
    ]]
    row_colors = []
    for c in report["claims"]:
        table_data.append([
            Paragraph(c["claim"], cell_style), Paragraph(c["best_match"], cell_style),
            Paragraph(str(c["similarity"]), cell_style), Paragraph(c["flag"].upper(), cell_style),
        ])
        row_colors.append(FLAG_COLORS.get(c["flag"], colors.black))

    table = Table(table_data, colWidths=[60 * mm, 60 * mm, 15 * mm, 25 * mm])
    style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f2a36")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dbe6e4")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafa")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]
    for i, col in enumerate(row_colors, start=1):
        style_commands.append(("TEXTCOLOR", (3, i), (3, i), col))
    table.setStyle(TableStyle(style_commands))

    elements.append(table)
    elements.append(Spacer(1, 10 * mm))
    elements.append(Paragraph(
        "This log was generated by VeriMed (Research Edition), the engine described and "
        "tested in the accompanying paper. All example data is either synthetic or a real, "
        "publicly licensed (CC-BY 4.0) clinical case report; no real patient data is processed.",
        meta_style,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
